version: '2'

services:
  cameradar:
    build: .
    container_name: cameradar
    volumes:
      - "./cameradar_thumbnails:/tmp/thumbs"
      - ".:/tmp/shared"
    environment:
     - CAMERAS_TARGET=localhost
     - CAMERAS_PORTS=554,8554
     - CACHE_MANAGER=dumb
     - MYSQL_ROOT_PASSWORD=root
  cameradar-database:
    container_name: cameradar-database
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=cmrdr
    ports:
     - "3306:3306"

volumes:
  mysql_data:
